//! Property-based test for the bounded-counter invariants that back the
//! per-host, per-store, and per-user concurrency limits (task 6.10).
//!
//! Feature: ZippyPanther, Property 6
//!
//! **Property 6: Bounded-counter invariants (per-host, per-store, per-user)**
//!
//! *For any* interleaving of acquire/release operations against a bounded
//! counter (per-origin-host in-flight requests, per-store active streams, or
//! per-user active connections), the live count never exceeds the configured
//! maximum, and once all operations complete the count returns to its
//! baseline.
//!
//! **Validates: Requirements 35.3, 20.3, 19.4, 19.5**
//!
//! ## What is under test
//!
//! All three bounded counters named by the property are realized by the same
//! primitive: a [`zippy_panther::resilience::bulkhead::Bulkhead`] semaphore pool
//! (design: Resilience → Pattern 3). The pool's `max_permits` is the bound;
//! [`Bulkhead::acquire`] hands back an RAII [`OwnedSemaphorePermit`] whose drop
//! returns the slot. This single primitive maps onto the three scopes the
//! property enumerates:
//!
//! * **per-origin-host in-flight requests** — `BulkheadKey::Host` (Req 35.3:
//!   cap concurrent in-flight upstream requests per origin host).
//! * **per-store active streams** — `BulkheadKey::Store`, whose `max_permits`
//!   *is* the per-store max-concurrent-streams value (Req 20.3).
//! * **per-user active connections** — modelled here as a distinct
//!   `BulkheadKey::Host("user:{id}")` pool. Req 19.4/19.5 bound a user's active
//!   content-proxy connections and decrement the count when the connection
//!   closes; the permit's RAII drop *is* that decrement-exactly-once (the
//!   `ConnGuard` pattern, Req 19.5).
//!
//! ## Distinction from Property 59 (task 6.9)
//!
//! Property 59 focuses on *cross-dependency isolation* (saturating one pool
//! never blocks another). This test instead drives an arbitrary interleaved
//! stream of acquire/release operations across three *scoped* pools
//! (host / store / user) and asserts the **counter [0, max] invariant** after
//! every single operation, plus the RAII guarantees that:
//!
//! * a release never over-decrements (the live count never goes negative — it
//!   is impossible to release a slot that was never acquired because a release
//!   here is the drop of a real held permit), and
//! * a dropped permit decrements **exactly once** (dropping the same permit
//!   reflects in the count one time; the available-permit total is conserved).
//!
//! Finally it asserts the baseline-restoration clause: after *all* held
//! permits are dropped, every pool returns to `in_flight == 0` /
//! `available == max`.
//!
//! ## Determinism
//!
//! `Bulkhead::acquire` is non-blocking (it `try_acquire_owned`s and fails fast
//! on saturation), so the model is a pure, deterministic counter — no real
//! time, no scheduler races. Each proptest case runs on its own current-thread
//! Tokio runtime; the operation sequence and pool maxima are generated by
//! proptest and replayed identically against a reference model and the real
//! pools.

use proptest::prelude::*;
use proptest::test_runner::TestCaseError;
use tokio::sync::OwnedSemaphorePermit;
use zippy_panther::errors::ErrorCategory;
use zippy_panther::resilience::bulkhead::{Bulkhead, BulkheadKey};

/// The three bounded-counter scopes the property enumerates. Each is a
/// distinct [`Bulkhead`] pool; the variants only select *which* pool an
/// operation targets.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Scope {
    /// Per-origin-host in-flight requests (Req 35.3).
    Host,
    /// Per-store active streams (Req 20.3).
    Store,
    /// Per-user active connections (Req 19.4 / 19.5, RAII ConnGuard).
    User,
}

impl Scope {
    const ALL: [Scope; 3] = [Scope::Host, Scope::Store, Scope::User];

    fn index(self) -> usize {
        match self {
            Scope::Host => 0,
            Scope::Store => 1,
            Scope::User => 2,
        }
    }

    /// A representative key for this scope's pool. Per-user is modelled as a
    /// `Host("user:…")` pool because the user connection limit shares the same
    /// bounded-counter primitive.
    fn key(self) -> BulkheadKey {
        match self {
            Scope::Host => BulkheadKey::Host("cdn.example.com".into()),
            Scope::Store => BulkheadKey::Store("realdebrid".into()),
            Scope::User => BulkheadKey::Host("user:42".into()),
        }
    }
}

/// One step of the interleaved sequence: try to acquire a permit on a scope, or
/// release a previously-held permit on a scope (a no-op if none is held — which
/// is exactly the "releases never over-decrement" guard).
#[derive(Clone, Copy, Debug)]
enum Op {
    Acquire(Scope),
    Release(Scope),
}

fn arb_scope() -> impl Strategy<Value = Scope> {
    prop_oneof![Just(Scope::Host), Just(Scope::Store), Just(Scope::User)]
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        arb_scope().prop_map(Op::Acquire),
        arb_scope().prop_map(Op::Release),
    ]
}

/// Build a per-case current-thread runtime. The pool API is `async` only to
/// match the outbound composition seam; it never actually yields, so a
/// single-threaded runtime fully and deterministically drives the property.
fn runtime() -> tokio::runtime::Runtime {
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("current-thread tokio runtime must build")
}

proptest! {
    // 256 cases (>= 100 required). Each case is pure in-memory counter work, so
    // a generous count stays fast while broadly exploring interleavings and
    // bounds (including the degenerate max == 0 pool).
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// Feature: ZippyPanther, Property 6 — bounded-counter invariants
    /// (per-host, per-store, per-user).
    /// **Validates: Requirements 35.3, 20.3, 19.4, 19.5**
    #[test]
    fn bounded_counter_invariants_hold_under_arbitrary_interleavings(
        // One bound per scope, including 0 (a pool that admits nothing) and
        // small values where saturation is frequently hit.
        host_max in 0usize..6,
        store_max in 0usize..6,
        user_max in 0usize..6,
        ops in proptest::collection::vec(arb_op(), 0..200),
    ) {
        let rt = runtime();
        let result: Result<(), TestCaseError> = rt.block_on(async move {
            let maxes = [host_max, store_max, user_max];

            // The three real bounded counters under test — one Bulkhead per
            // scope. Per-user/per-host/per-store are modelled as distinct
            // pools sharing the same semaphore primitive (design: Pattern 3).
            let pools: Vec<Bulkhead> = Scope::ALL
                .iter()
                .map(|s| Bulkhead::new(s.key(), maxes[s.index()]))
                .collect();

            // Reference model of each pool's live count, advanced in lock-step
            // with the real pools so we can assert the real `in_flight()`
            // equals the model after every operation.
            let mut model_live = [0usize; 3];
            // Permits we currently hold per scope (dropping one is a release).
            let mut held: [Vec<OwnedSemaphorePermit>; 3] =
                [Vec::new(), Vec::new(), Vec::new()];

            // -- Invariants checked after every single operation -------------
            for (step, op) in ops.into_iter().enumerate() {
                match op {
                    Op::Acquire(scope) => {
                        let i = scope.index();
                        let pool = &pools[i];
                        let bound = maxes[i];

                        match pool.acquire().await {
                            Ok(permit) => {
                                // A successful acquire is only possible when
                                // there was spare capacity — the bound is never
                                // exceeded (Req 35.3 / 20.3).
                                prop_assert!(
                                    model_live[i] < bound,
                                    "step {}: {:?} acquired a permit at/above max \
                                     (model_live={}, bound={})",
                                    step, scope, model_live[i], bound,
                                );
                                held[i].push(permit);
                                model_live[i] += 1;
                            }
                            Err(err) => {
                                // Acquire only fails when the pool is saturated;
                                // it is a fail-fast UpstreamUnavailable and the
                                // count is pinned at the bound (never above).
                                prop_assert_eq!(
                                    model_live[i], bound,
                                    "step {}: {:?} acquire failed but the pool was \
                                     not full (model_live={}, bound={})",
                                    step, scope, model_live[i], bound,
                                );
                                prop_assert_eq!(
                                    err.category,
                                    ErrorCategory::UpstreamUnavailable,
                                    "step {}: {:?} saturation must be a fail-fast \
                                     UpstreamUnavailable",
                                    step, scope,
                                );
                            }
                        }
                    }
                    Op::Release(scope) => {
                        let i = scope.index();
                        // Dropping a held permit decrements exactly once
                        // (RAII ConnGuard, Req 19.5). If nothing is held the
                        // release is a no-op — a release can never
                        // over-decrement below the baseline (Req 19.5: the
                        // count decrements when a connection closes, and only
                        // then).
                        if let Some(permit) = held[i].pop() {
                            drop(permit);
                            model_live[i] -= 1;
                        }
                    }
                }

                // After every op, every counter is within [0, max] AND the real
                // pool agrees with the model exactly (decrement-exactly-once
                // and no over-decrement both follow from this equality holding
                // step after step).
                for scope in Scope::ALL {
                    let i = scope.index();
                    let pool = &pools[i];
                    let bound = maxes[i];

                    // [0, max]: in_flight() is unsigned so >= 0 is structural;
                    // the meaningful half is the upper bound.
                    prop_assert!(
                        pool.in_flight() <= bound,
                        "step {}: {:?} live count {} exceeded max {}",
                        step, scope, pool.in_flight(), bound,
                    );
                    // Real pool tracks the model precisely.
                    prop_assert_eq!(
                        pool.in_flight(), model_live[i],
                        "step {}: {:?} real in_flight diverged from model",
                        step, scope,
                    );
                    // Conservation: available + in_flight == max at all times.
                    prop_assert_eq!(
                        pool.available_permits() + pool.in_flight(),
                        bound,
                        "step {}: {:?} available+in_flight must equal max",
                        step, scope,
                    );
                }
            }

            // -- Baseline restoration ---------------------------------------
            // Release everything still held; the count must return to its
            // baseline of zero (all slots back, available == max).
            for scope in Scope::ALL {
                let i = scope.index();
                held[i].clear(); // drops all remaining permits (RAII release)
                let pool = &pools[i];
                prop_assert_eq!(
                    pool.in_flight(), 0,
                    "{:?}: live count must return to baseline once all \
                     operations complete",
                    scope,
                );
                prop_assert_eq!(
                    pool.available_permits(), maxes[i],
                    "{:?}: all permits must be available again at baseline",
                    scope,
                );
            }

            Ok(())
        });
        result?;
    }
}
